server:
    port: ${PORT:8850}

spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/Adr-Luceros/Config-global-microservice.git
